name: 02-my-second-workflow

on: push

jobs:
    second_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
          
        - name: List and Read file  
          run: | 
             echo "my first github action Job"
             ls -ltra
             cat README.md
        - name: Install cowsay program
          run: sudo apt-get install cowsay -y     

        - name: Generate ASCII artworkf
          run : cowsay -f dragon "run for cover, I am DRAGON ..RAWR" >> dragon.txt
        - name: Test file exists
          run: grep -i "dragon" dragon.txt
        - name: Read File 
          run: cat dragon.txt
        - name: List repo Files
          run: ls -ltra
                


              