name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      run_job:
        type: boolean
        required: false
        description: Run specific job 
      custom_message:
        type: string
        required: true
        description: Enter a custom message



jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"
  job2:
    runs-on: ubuntu-latest
    steps: 
      - name: Printing custom message 
        run: echo ${{ inputs.custom_message }}  
